CREATE DATABASE SFSDB;
GO
USE SFSDB;
CREATE TABLE FileObject
(
	Id BIGINT PRIMARY KEY NOT NULL,
	FileType NVARCHAR(50),
	IsDeleted BIT NOT NULL DEFAULT 0,
	FilePath NVARCHAR(1000) NOT NULL,
	LastModified DATETIME NOT NULL DEFAULT GETUTCDATE(),
);
CREATE INDEX IX_FileObject_FileType ON FileObject(FileType) WHERE FileType IS NOT NULL AND IsDeleted = 0;