CREATE DATABASE SpoofSettingsService;
GO
USE SpoofSettingsService;

CREATE TABLE [User]
(
	Id BIGINT CONSTRAINT PK_User_Id PRIMARY KEY IDENTITY,
	WasOnline DATETIME NOT NULL DEFAULT GETUTCDATE(),
	[Name] NVARCHAR(100) NOT NULL,
	MonthsBeforeDelete BIGINT NOT NULL DEFAULT(6),
	SearchMe BIT NOT NULL DEFAULT(1),
	ShowMe BIT NOT NULL DEFAULT(1),
	ForwardMessage BIT NOT NULL DEFAULT(1),
	InviteMe BIT NOT NULL DEFAULT(1),
	IsDeleted BIT NOT NULL DEFAULT 0,
);

CREATE TABLE ChatType
(
	Id BIGINT CONSTRAINT PK_ChatType_Id PRIMARY KEY IDENTITY,
	Title NVARCHAR(50) UNIQUE NOT NULL,
);

CREATE TABLE RoleType
(
	Id BIGINT CONSTRAINT PK_RoleType_Id PRIMARY KEY IDENTITY,
	Title NVARCHAR(50) UNIQUE NOT NULL,
	SendMessage BIT NOT NULL DEFAULT 0,
	ReceiveMessage BIT NOT NULL DEFAULT 0,
	ManageChat BIT NOT NULL DEFAULT 0,
	ForwardMessage BIT NOT NULl DEFAULT 0,
);
GO
CREATE TABLE Chat
(
    Id BIGINT CONSTRAINT PK_Chat_Id PRIMARY KEY IDENTITY,
    ChatTypeId BIGINT CONSTRAINT FK_Chat_ChatTypeId FOREIGN KEY REFERENCES ChatType(Id) NOT NULL,
	OwnerId BIGINT CONSTRAINT FK_Chat_OwnerId FOREIGN KEY REFERENCES [User](Id),
    ChatName NVARCHAR(100),
    IsPublic BIT DEFAULT 1,
	UniqueName NVARCHAR(100) UNIQUE,
    CreatedAt DATETIME NOT NULL DEFAULT GETUTCDATE(),
    LastModified DATETIME NOT NULL DEFAULT GETUTCDATE(),
	IsDeleted BIT NOT NULL DEFAULT 0,
);
GO

CREATE TABLE Extension
(
	Id INT CONSTRAINT PK_Extension_Id PRIMARY KEY IDENTITY,
	FileCategory TINYINT NOT NULL,
	Title NVARCHAR(100) NOT NULL,
);
GO

CREATE TABLE FileMetadata (
    Id BIGINT CONSTRAINT PK_FileMetadata_Id PRIMARY KEY,
    Bucket NVARCHAR(50) NOT NULL, -- 'avatars', 'stickers'
    ObjectKey NVARCHAR(500) NOT NULL,
	ExtensionId INT CONSTRAINT PK_FileMetadata_ExtensionId FOREIGN KEY REFERENCES Extension(Id) NOT NULL,
);

CREATE TABLE ChatUser
(
	Id BIGINT CONSTRAINT PK_ChatUser_Id PRIMARY KEY IDENTITY,
    ChatId BIGINT CONSTRAINT FK_ChatUser_ChatId FOREIGN KEY REFERENCES Chat(Id) NOT NULL,
    UserId BIGINT CONSTRAINT FK_ChatUser_UserId FOREIGN KEY REFERENCES [User](Id) NOT NULL,
    RoleTypeId BIGINT CONSTRAINT FK_ChatUser_RoleTypeId FOREIGN KEY REFERENCES RoleType(Id) NOT NULL,
	JoinedAt DATETIME NOT NULL DEFAULT GETUTCDATE(),
	IsMutted BIT NOT NULL DEFAULT(0),
	IsDeleted BIT NOT NULL DEFAULT(0),
);
GO
CREATE UNIQUE INDEX UX_ChatUser_ChatId_UserId ON ChatUser(ChatId, UserId) WHERE IsDeleted = 0
CREATE INDEX IX_ChatUser_UserChat ON ChatUser(UserId, ChatId) WHERE IsDeleted = 0;
CREATE INDEX IX_ChatUser_ChatId ON ChatUser(ChatId) WHERE IsDeleted = 0;

CREATE TABLE StickerPack
(
	Id BIGINT CONSTRAINT PK_StickerPack_Id PRIMARY KEY IDENTITY,
	AuthorId BIGINT CONSTRAINT FK_StickerPack_AuthorId FOREIGN KEY REFERENCES [User](Id),
	Title NVARCHAR(100) NOT NULL,
	PreviewId BIGINT CONSTRAINT FK_StickerPack_PreviewId FOREIGN KEY REFERENCES FileMetadata(Id),
	LastModified DATETIME NOT NULL DEFAULT GETUTCDATE(),
	IsDeleted BIT NOT NULL DEFAULT 0,
);
GO
CREATE INDEX IX_StickerPack_AuthorId ON StickerPack(AuthorId) WHERE IsDeleted = 0;

CREATE TABLE Sticker
(
	Id BIGINT CONSTRAINT PK_Sticker_Id PRIMARY KEY IDENTITY,
	StickerPackId BIGINT CONSTRAINT FK_Sticker_StickerPackId FOREIGN KEY REFERENCES StickerPack(Id) NOT NULL,
	FileId BIGINT CONSTRAINT FK_Sticker_FileId FOREIGN KEY REFERENCES FileMetadata(Id),
	Title NVARCHAR(50) NOT NULL,
	LastModified DATETIME NOT NULL DEFAULT GETUTCDATE(),
	IsDeleted BIT NOT NULL DEFAULT 0,
);

CREATE TABLE UserAvatar
(
	Id BIGINT CONSTRAINT PK_UserAvatar_Id PRIMARY KEY IDENTITY,
	UserId BIGINT CONSTRAINT FK_UserAvatar_UserId FOREIGN KEY REFERENCES [User](Id),
	FileId BIGINT CONSTRAINT FK_UserAvatar_FileId FOREIGN KEY REFERENCES FileMetadata(Id),
	IsActive BIT NOT NULL DEFAULT 1,
	IsDeleted BIT NOT NULL DEFAULT 0,
	LastModified DATETIME NOT NULL DEFAULT GETUTCDATE(),
);

CREATE TABLE ChatAvatar
(
	Id BIGINT CONSTRAINT PK_ChatAvatar_Id PRIMARY KEY IDENTITY,
	ChatId BIGINT CONSTRAINT FK_ChatAvatar_ChatId FOREIGN KEY REFERENCES Chat(Id),
	FileId BIGINT CONSTRAINT FK_ChatAvatar_FileId FOREIGN KEY REFERENCES FileMetadata(Id),
	IsActive BIT NOT NULL DEFAULT 1,
	IsDeleted BIT NOT NULL DEFAULT 0,
	LastModified DATETIME NOT NULL DEFAULT GETUTCDATE(),
);
